run:
  go: 1.20
  tests: true
  skip-dirs:
    - go
#    - ../../../go
#    - ../../../../../opt
    - /opt
linters:
  enable:
    - cyclop
    - gocyclo
    - gocognit
    - dupl
    - dupword
    - godot
    - ireturn